# Generated by Django 4.0.2 on 2022-02-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128)),
                ('model_img', models.TextField()),
            ],
            options={
                'db_table': 'info',
            },
        ),
    ]
